[package]
name = "personal-fortune"
version = "0.2.0"
authors = ["Nat Knight <nathaniel.ep@gmail.com>"]
edition = "2018"

[dependencies]
rusqlite = {version = "*", features=["bundled"]}
simple-server = "0.4"